"""adicionando todos a tabela de users

Revision ID: 96b84e24bb72
Revises: 2cac4be6e22c
Create Date: 2025-08-26 08:13:03.849401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b84e24bb72'
down_revision: Union[str, Sequence[str], None] = '2cac4be6e22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
