"""add updated_at in models User and default=func.now()

Revision ID: cdd0a79e6a3c
Revises: a757bd9be833
Create Date: 2025-06-30 14:30:43.899363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd0a79e6a3c'
down_revision: Union[str, Sequence[str], None] = 'a757bd9be833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
